### PR TITLE
feature(rcrs): adds new option to position some countries at the top of the dropdown as a main options

### PR DESCRIPTION
**Pull request by Lucianova**
```
<CountryDropdown
            valueType="short"
            value={value}
            mainOptions={['US', 'CN', 'MX']}
            onChange={onChange}
            classes={classname('form-input--bordered', 'form-input--rounded')}
        />)
```
sin titulo

### CODE REVIEW

**Comment by xfsnowind** [comment]
@Lucianova I also need this feature to display some preferred countries in the top, but it seems your codes has conflict and not finished.

**Comment by xfsnowind** [comment]
@benkeen just checked the codes, it seems it should be able to work, or maybe it can consider the case of both shortcodes and fullname of countries. But is that possible to merge and release new one?

**Comment by benkeen** [comment]
Hey @xfsnowind - I'm so sorry for missing this. I'll look this over this week & get back to you.

**Comment by benkeen** [comment]
Ugh, I'm exceedingly sorry I didn't get back to you :( Too many projects. If you have time to rebase this against the latest code, go for it. If not, let me know and I can do it.

**Comment by zimmelbc** [comment]
Hello - any chance this can be merged and released? Customer requested for this exact feature. Thank you!

**Comment by benkeen** [comment]
Hey @zimmelbc - yeah this is a nice feature, agreed! Okay I'll get this in in the next few days. If I haven't got a fresh release out by the end of the weekend just pop back here and yell at me. :)

**Comment by benkeen** [comment]
This feature has been added in 1.4.2. See the `priorityOptions` prop for <CountryDropdown />. Thanks again for the PR @Lucianova! Based it on your code.

**Comment by zimmelbc** [comment]
Pulled 1.4.2 and feature works great! Thank you @benkeen  and @Lucianova!

**Comment by Lucianova** [comment]
😃

**Pull request closed without merging**
