### PR TITLE
Added type files for Typescript

### PR DESCRIPTION
**Pull request by KyleDavisDev**
Added type file for Typescript users. File based off of README file.

### CODE REVIEW

**Comment by benkeen** [comment]
Thanks @KyleDavisDev!

**Comment by jaredh159** [comment]
@benkeen any chance we could get a release containing the type defs?  Thanks for the great project!

**Comment by benkeen** [comment]
Ooh yeah totally. I'll get a new version out today, thanks for the reminder.

**Comment by KyleDavisDev** [comment]
If there are any issues with the type files, please let me know and I will look into it when I can.

**Comment by benkeen** [comment]
Sorry, gotta bump this to tomorrow night.

**Comment by benkeen** [comment]
I just released 1.4.6 which includes the typings. Sorry for the wait on that. 

I'd actually like to convert the whole script to TS at some point. Perhaps the NY!

**Comment by jaredh159** [comment]
@benkeen thanks so much for the release!  I just pulled it down and it looks like the `index.d.ts` file isn't getting included in the published package, so types still aren't working.  Probably something about the build process or what rollup is doing, not exactly sure.  No hurry or anything, just wanted to let you know!

**Comment by benkeen** [comment]
Drat, sorry about that! Try 1.4.7. That now includes the file properly.

**Comment by jaredh159** [comment]
@benkeen works well now, thanks so much!

**Pull request merged**
